GET http://localhost:3333/

###
GET http://localhost:3333/all-movies


### 
POST http://localhost:3333/create-task
Content-Type: application/json

{
    "id": "12",
    "name": "Duna: Parte 2",
    "genero": "ficcao",
    "duracao": "24540",
    "classificacaoetaria": "1"
}

###
PUT http://localhost:3333/update-task/2
Content-Type: application/json

{
    "name": "Homem Aranha: Sem Volta Para Casa",
    "genero": "Ação e Ficção",
    "duracao": "23000",
    "classificacaoetaria": "12"
}

### 
DELETE http://localhost:3333/delete-task/2
